- hosts: nextcloud
  become: true
  tasks:
    - name: update repos
      apt:
       update_cache: yes

    - name: upgrade distribution
      apt:
       upgrade: dist

    - name: Install apache2
      apt:
       name: apache2
       state: latest   

    - name: Open port 80 on iptable
      iptables:
       chain: INPUT
       protocol: tcp
       destination_port: 80
       jump: ACCEPT
       action: insert
       rule_num: 1
